const products = [
  {
    id: 1,
    name: "PS Monitor",
    sku: "56e673",
    category: "gaming",
    brand: "PlayStation",
    quantity: "10",
    price: "800000",
    description: "lorem ipsum sit7 wertwyrtwh ytfiuwhiufyi",
    image:
      "https://res.cloudinary.com/ddsyqq7er/image/upload/v1701285830/bamstore/llhgoihfokkarbkjtmbf.png",
    regularPrice: "30,000",
    color: "black",
    stock: 0,
  },
  {
    id: 2,
    name: "Charger",
    sku: "56e673",
    category: "accessories",
    brand: "Onikuma",
    quantity: "5",
    price: "21000",
    description: "lorem ipsum sit",
    image:
      "https://res.cloudinary.com/ddsyqq7er/image/upload/v1695682140/bamstore/phone_gio4ji.png",
    regularPrice: "30000",
    color: "black",
    stock: 30,
  },
  {
    id: 3,
    name: "PS4 Console",
    sku: "56e673",
    category: "gaming",
    brand: "iphone",
    quantity: "10",
    price: "5,000",
    description: "lorem ipsum sit",
    image:
      "https://res.cloudinary.com/ddsyqq7er/image/upload/v1701296457/bamstore/j5xgsyk1yqybkcauec7s.png",
    regularPrice: "30000",
    color: "black",
  },
  {
    id: 4,
    name: "PS5 Console",
    sku: "56e673",
    category: "gaming",
    brand: "Ps4",
    quantity: "10",
    price: "225000",
    description: "lorem ipsum sit",
    image:
      "https://res.cloudinary.com/ddsyqq7er/image/upload/v1701296385/bamstore/lz55tnqjncw13u22z66z.png",
    regularPrice: "300,000",
    color: "black",
  },
  {
    id: 5,
    name: "PS5 Controller",
    sku: "56e673",
    category: "accessories",
    brand: "PlayStation",
    quantity: "10",
    price: "25,000",
    description: "lorem ipsum sit",
    image:
      "https://res.cloudinary.com/ddsyqq7er/image/upload/v1701285693/bamstore/x8ks7vdra96xprdqmfbd.png",
    regularPrice: "30000",
    color: "black",
  },
  {
    id: 6,
    name: "Large Gaming Pad",
    sku: "56e673",
    category: "workspace",
    brand: "Orico",
    quantity: "10",
    price: "6000",
    description: "lorem ipsum sit",
    image:
      "https://res.cloudinary.com/ddsyqq7er/image/upload/v1701548532/bamstore/c8z7sluuivy7e7rjyk2c.jpg",
    regularPrice: "30,000",
    color: "black",
  },
  {
    id: 7,
    name: "PS4 Controller",
    sku: "56e673",
    category: "accessories",
    brand: "PlayStation",
    quantity: "40",
    price: "25000",
    description: "lorem ipsum sit",
    image:
      "https://res.cloudinary.com/ddsyqq7er/image/upload/v1701287000/bamstore/a5wiz8ec8markqxqhuoi.png",
    regularPrice: "30,000",
    color: "black",
  },
  {
    id: 8,
    name: "HDMI Switch",
    sku: "56e673",
    category: ["accessories", "workspace"],
    brand: "Orico",
    quantity: "40",
    price: "10000",
    description: "lorem ipsum sit",
    image:
      "https://res.cloudinary.com/ddsyqq7er/image/upload/v1701548541/bamstore/iomfyn584ouf6xwt7cbs.jpg",
    regularPrice: "30,000",
    color: "black",
  },
  {
    id: 9,
    name: "Type-C Cable",
    sku: "56e673",
    category: "accessories",
    brand: "Orico",
    quantity: "5",
    price: "4000",
    description: "lorem ipsum sit",
    image:
      "https://res.cloudinary.com/ddsyqq7er/image/upload/v1701547917/bamstore/jcrdaj302ackrzrhm0gc.jpg",
    regularPrice: "30,000",
    color: "black",
  },
  {
    id: 10,
    name: "Laptop Stand",
    sku: "56e673",
    category: ["accessories", "workspace"],
    brand: "Orico",
    quantity: "40",
    price: "30000",
    description: "Orico laptop stand 360 degree",
    image:
      "https://res.cloudinary.com/ddsyqq7er/image/upload/v1701548445/bamstore/hyynbwcor1wg6wavzit8.jpg",
    regularPrice: "30,000",
    color: "black",
  },
];

module.exports = products;
